/**
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Branding_getAutocomplete_v2_Response_mPayload.h
 *
 * Payload for POST /2/object/branding/getAutocomplete
 */

#ifndef Branding_getAutocomplete_v2_Response_mPayload_H
#define Branding_getAutocomplete_v2_Response_mPayload_H

#include <QJsonObject>

#include "Branding_AutocompleteElement_Response.h"
#include <QList>

#include "Enum.h"
#include "Object.h"

namespace Ezmaxapi {
class Branding_AutocompleteElement_Response;

class Branding_getAutocomplete_v2_Response_mPayload : public Object {
public:
    Branding_getAutocomplete_v2_Response_mPayload();
    Branding_getAutocomplete_v2_Response_mPayload(QString json);
    ~Branding_getAutocomplete_v2_Response_mPayload() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QList<Branding_AutocompleteElement_Response> getAObjBranding() const;
    void setAObjBranding(const QList<Branding_AutocompleteElement_Response> &a_obj_branding);
    bool is_a_obj_branding_Set() const;
    bool is_a_obj_branding_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QList<Branding_AutocompleteElement_Response> m_a_obj_branding;
    bool m_a_obj_branding_isSet;
    bool m_a_obj_branding_isValid;
};

} // namespace Ezmaxapi

Q_DECLARE_METATYPE(Ezmaxapi::Branding_getAutocomplete_v2_Response_mPayload)

#endif // Branding_getAutocomplete_v2_Response_mPayload_H
