/**
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Branding_getObject_v2_Response_mPayload.h
 *
 * Payload for GET /2/object/branding/{pkiBrandingID}
 */

#ifndef Branding_getObject_v2_Response_mPayload_H
#define Branding_getObject_v2_Response_mPayload_H

#include <QJsonObject>

#include "Branding_ResponseCompound.h"

#include "Enum.h"
#include "Object.h"

namespace Ezmaxapi {
class Branding_ResponseCompound;

class Branding_getObject_v2_Response_mPayload : public Object {
public:
    Branding_getObject_v2_Response_mPayload();
    Branding_getObject_v2_Response_mPayload(QString json);
    ~Branding_getObject_v2_Response_mPayload() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    Branding_ResponseCompound getObjBranding() const;
    void setObjBranding(const Branding_ResponseCompound &obj_branding);
    bool is_obj_branding_Set() const;
    bool is_obj_branding_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    Branding_ResponseCompound m_obj_branding;
    bool m_obj_branding_isSet;
    bool m_obj_branding_isValid;
};

} // namespace Ezmaxapi

Q_DECLARE_METATYPE(Ezmaxapi::Branding_getObject_v2_Response_mPayload)

#endif // Branding_getObject_v2_Response_mPayload_H
