/**
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.2.1
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "Creditcardclient_createObject_v1_Request.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "Helpers.h"

namespace Ezmaxapi {

Creditcardclient_createObject_v1_Request::Creditcardclient_createObject_v1_Request(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

Creditcardclient_createObject_v1_Request::Creditcardclient_createObject_v1_Request() {
    this->initializeModel();
}

Creditcardclient_createObject_v1_Request::~Creditcardclient_createObject_v1_Request() {}

void Creditcardclient_createObject_v1_Request::initializeModel() {

    m_a_obj_creditcardclient_isSet = false;
    m_a_obj_creditcardclient_isValid = false;
}

void Creditcardclient_createObject_v1_Request::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void Creditcardclient_createObject_v1_Request::fromJsonObject(QJsonObject json) {

    m_a_obj_creditcardclient_isValid = ::Ezmaxapi::fromJsonValue(m_a_obj_creditcardclient, json[QString("a_objCreditcardclient")]);
    m_a_obj_creditcardclient_isSet = !json[QString("a_objCreditcardclient")].isNull() && m_a_obj_creditcardclient_isValid;
}

QString Creditcardclient_createObject_v1_Request::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject Creditcardclient_createObject_v1_Request::asJsonObject() const {
    QJsonObject obj;
    if (m_a_obj_creditcardclient.size() > 0) {
        obj.insert(QString("a_objCreditcardclient"), ::Ezmaxapi::toJsonValue(m_a_obj_creditcardclient));
    }
    return obj;
}

QList<Creditcardclient_RequestCompound> Creditcardclient_createObject_v1_Request::getAObjCreditcardclient() const {
    return m_a_obj_creditcardclient;
}
void Creditcardclient_createObject_v1_Request::setAObjCreditcardclient(const QList<Creditcardclient_RequestCompound> &a_obj_creditcardclient) {
    m_a_obj_creditcardclient = a_obj_creditcardclient;
    m_a_obj_creditcardclient_isSet = true;
}

bool Creditcardclient_createObject_v1_Request::is_a_obj_creditcardclient_Set() const{
    return m_a_obj_creditcardclient_isSet;
}

bool Creditcardclient_createObject_v1_Request::is_a_obj_creditcardclient_Valid() const{
    return m_a_obj_creditcardclient_isValid;
}

bool Creditcardclient_createObject_v1_Request::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_a_obj_creditcardclient.size() > 0) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool Creditcardclient_createObject_v1_Request::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_a_obj_creditcardclient_isValid && true;
}

} // namespace Ezmaxapi
