/**
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.2.2
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Discussionmembership_createObject_v1_Request.h
 *
 * Request for POST /1/object/discussionmembership
 */

#ifndef Discussionmembership_createObject_v1_Request_H
#define Discussionmembership_createObject_v1_Request_H

#include <QJsonObject>

#include "Discussionmembership_RequestCompound.h"
#include <QList>

#include "Enum.h"
#include "Object.h"

namespace Ezmaxapi {
class Discussionmembership_RequestCompound;

class Discussionmembership_createObject_v1_Request : public Object {
public:
    Discussionmembership_createObject_v1_Request();
    Discussionmembership_createObject_v1_Request(QString json);
    ~Discussionmembership_createObject_v1_Request() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QList<Discussionmembership_RequestCompound> getAObjDiscussionmembership() const;
    void setAObjDiscussionmembership(const QList<Discussionmembership_RequestCompound> &a_obj_discussionmembership);
    bool is_a_obj_discussionmembership_Set() const;
    bool is_a_obj_discussionmembership_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QList<Discussionmembership_RequestCompound> m_a_obj_discussionmembership;
    bool m_a_obj_discussionmembership_isSet;
    bool m_a_obj_discussionmembership_isValid;
};

} // namespace Ezmaxapi

Q_DECLARE_METATYPE(Ezmaxapi::Discussionmembership_createObject_v1_Request)

#endif // Discussionmembership_createObject_v1_Request_H
