/**
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Ezsigntemplatepackagemembership_ResponseCompound.h
 *
 * A Ezsigntemplatepackagemembership Object
 */

#ifndef Ezsigntemplatepackagemembership_ResponseCompound_H
#define Ezsigntemplatepackagemembership_ResponseCompound_H

#include <QJsonObject>

#include "Ezsigntemplate_ResponseCompound.h"
#include "Ezsigntemplatepackagesignermembership_ResponseCompound.h"
#include <QList>

#include "Enum.h"
#include "Object.h"

namespace Ezmaxapi {
class Ezsigntemplate_ResponseCompound;
class Ezsigntemplatepackagesignermembership_ResponseCompound;

class Ezsigntemplatepackagemembership_ResponseCompound : public Object {
public:
    Ezsigntemplatepackagemembership_ResponseCompound();
    Ezsigntemplatepackagemembership_ResponseCompound(QString json);
    ~Ezsigntemplatepackagemembership_ResponseCompound() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    qint32 getPkiEzsigntemplatepackagemembershipId() const;
    void setPkiEzsigntemplatepackagemembershipId(const qint32 &pki_ezsigntemplatepackagemembership_id);
    bool is_pki_ezsigntemplatepackagemembership_id_Set() const;
    bool is_pki_ezsigntemplatepackagemembership_id_Valid() const;

    qint32 getFkiEzsigntemplatepackageId() const;
    void setFkiEzsigntemplatepackageId(const qint32 &fki_ezsigntemplatepackage_id);
    bool is_fki_ezsigntemplatepackage_id_Set() const;
    bool is_fki_ezsigntemplatepackage_id_Valid() const;

    qint32 getFkiEzsigntemplateId() const;
    void setFkiEzsigntemplateId(const qint32 &fki_ezsigntemplate_id);
    bool is_fki_ezsigntemplate_id_Set() const;
    bool is_fki_ezsigntemplate_id_Valid() const;

    qint32 getIEzsigntemplatepackagemembershipOrder() const;
    void setIEzsigntemplatepackagemembershipOrder(const qint32 &i_ezsigntemplatepackagemembership_order);
    bool is_i_ezsigntemplatepackagemembership_order_Set() const;
    bool is_i_ezsigntemplatepackagemembership_order_Valid() const;

    Ezsigntemplate_ResponseCompound getObjEzsigntemplate() const;
    void setObjEzsigntemplate(const Ezsigntemplate_ResponseCompound &obj_ezsigntemplate);
    bool is_obj_ezsigntemplate_Set() const;
    bool is_obj_ezsigntemplate_Valid() const;

    QList<Ezsigntemplatepackagesignermembership_ResponseCompound> getAObjEzsigntemplatepackagesignermembership() const;
    void setAObjEzsigntemplatepackagesignermembership(const QList<Ezsigntemplatepackagesignermembership_ResponseCompound> &a_obj_ezsigntemplatepackagesignermembership);
    bool is_a_obj_ezsigntemplatepackagesignermembership_Set() const;
    bool is_a_obj_ezsigntemplatepackagesignermembership_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    qint32 m_pki_ezsigntemplatepackagemembership_id;
    bool m_pki_ezsigntemplatepackagemembership_id_isSet;
    bool m_pki_ezsigntemplatepackagemembership_id_isValid;

    qint32 m_fki_ezsigntemplatepackage_id;
    bool m_fki_ezsigntemplatepackage_id_isSet;
    bool m_fki_ezsigntemplatepackage_id_isValid;

    qint32 m_fki_ezsigntemplate_id;
    bool m_fki_ezsigntemplate_id_isSet;
    bool m_fki_ezsigntemplate_id_isValid;

    qint32 m_i_ezsigntemplatepackagemembership_order;
    bool m_i_ezsigntemplatepackagemembership_order_isSet;
    bool m_i_ezsigntemplatepackagemembership_order_isValid;

    Ezsigntemplate_ResponseCompound m_obj_ezsigntemplate;
    bool m_obj_ezsigntemplate_isSet;
    bool m_obj_ezsigntemplate_isValid;

    QList<Ezsigntemplatepackagesignermembership_ResponseCompound> m_a_obj_ezsigntemplatepackagesignermembership;
    bool m_a_obj_ezsigntemplatepackagesignermembership_isSet;
    bool m_a_obj_ezsigntemplatepackagesignermembership_isValid;
};

} // namespace Ezmaxapi

Q_DECLARE_METATYPE(Ezmaxapi::Ezsigntemplatepackagemembership_ResponseCompound)

#endif // Ezsigntemplatepackagemembership_ResponseCompound_H
