/**
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.2.2
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "Ezsignimportfolder_getObject_v2_Response_mPayload.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "Helpers.h"

namespace Ezmaxapi {

Ezsignimportfolder_getObject_v2_Response_mPayload::Ezsignimportfolder_getObject_v2_Response_mPayload(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

Ezsignimportfolder_getObject_v2_Response_mPayload::Ezsignimportfolder_getObject_v2_Response_mPayload() {
    this->initializeModel();
}

Ezsignimportfolder_getObject_v2_Response_mPayload::~Ezsignimportfolder_getObject_v2_Response_mPayload() {}

void Ezsignimportfolder_getObject_v2_Response_mPayload::initializeModel() {

    m_obj_ezsignimportfolder_isSet = false;
    m_obj_ezsignimportfolder_isValid = false;
}

void Ezsignimportfolder_getObject_v2_Response_mPayload::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void Ezsignimportfolder_getObject_v2_Response_mPayload::fromJsonObject(QJsonObject json) {

    m_obj_ezsignimportfolder_isValid = ::Ezmaxapi::fromJsonValue(m_obj_ezsignimportfolder, json[QString("objEzsignimportfolder")]);
    m_obj_ezsignimportfolder_isSet = !json[QString("objEzsignimportfolder")].isNull() && m_obj_ezsignimportfolder_isValid;
}

QString Ezsignimportfolder_getObject_v2_Response_mPayload::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject Ezsignimportfolder_getObject_v2_Response_mPayload::asJsonObject() const {
    QJsonObject obj;
    if (m_obj_ezsignimportfolder.isSet()) {
        obj.insert(QString("objEzsignimportfolder"), ::Ezmaxapi::toJsonValue(m_obj_ezsignimportfolder));
    }
    return obj;
}

Ezsignimportfolder_ResponseCompound Ezsignimportfolder_getObject_v2_Response_mPayload::getObjEzsignimportfolder() const {
    return m_obj_ezsignimportfolder;
}
void Ezsignimportfolder_getObject_v2_Response_mPayload::setObjEzsignimportfolder(const Ezsignimportfolder_ResponseCompound &obj_ezsignimportfolder) {
    m_obj_ezsignimportfolder = obj_ezsignimportfolder;
    m_obj_ezsignimportfolder_isSet = true;
}

bool Ezsignimportfolder_getObject_v2_Response_mPayload::is_obj_ezsignimportfolder_Set() const{
    return m_obj_ezsignimportfolder_isSet;
}

bool Ezsignimportfolder_getObject_v2_Response_mPayload::is_obj_ezsignimportfolder_Valid() const{
    return m_obj_ezsignimportfolder_isValid;
}

bool Ezsignimportfolder_getObject_v2_Response_mPayload::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_obj_ezsignimportfolder.isSet()) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool Ezsignimportfolder_getObject_v2_Response_mPayload::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_obj_ezsignimportfolder_isValid && true;
}

} // namespace Ezmaxapi
