/**
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "Ezsignformfieldgroup_editObject_v1_Request.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "Helpers.h"

namespace Ezmaxapi {

Ezsignformfieldgroup_editObject_v1_Request::Ezsignformfieldgroup_editObject_v1_Request(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

Ezsignformfieldgroup_editObject_v1_Request::Ezsignformfieldgroup_editObject_v1_Request() {
    this->initializeModel();
}

Ezsignformfieldgroup_editObject_v1_Request::~Ezsignformfieldgroup_editObject_v1_Request() {}

void Ezsignformfieldgroup_editObject_v1_Request::initializeModel() {

    m_obj_ezsignformfieldgroup_isSet = false;
    m_obj_ezsignformfieldgroup_isValid = false;
}

void Ezsignformfieldgroup_editObject_v1_Request::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void Ezsignformfieldgroup_editObject_v1_Request::fromJsonObject(QJsonObject json) {

    m_obj_ezsignformfieldgroup_isValid = ::Ezmaxapi::fromJsonValue(m_obj_ezsignformfieldgroup, json[QString("objEzsignformfieldgroup")]);
    m_obj_ezsignformfieldgroup_isSet = !json[QString("objEzsignformfieldgroup")].isNull() && m_obj_ezsignformfieldgroup_isValid;
}

QString Ezsignformfieldgroup_editObject_v1_Request::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject Ezsignformfieldgroup_editObject_v1_Request::asJsonObject() const {
    QJsonObject obj;
    if (m_obj_ezsignformfieldgroup.isSet()) {
        obj.insert(QString("objEzsignformfieldgroup"), ::Ezmaxapi::toJsonValue(m_obj_ezsignformfieldgroup));
    }
    return obj;
}

Ezsignformfieldgroup_RequestCompound Ezsignformfieldgroup_editObject_v1_Request::getObjEzsignformfieldgroup() const {
    return m_obj_ezsignformfieldgroup;
}
void Ezsignformfieldgroup_editObject_v1_Request::setObjEzsignformfieldgroup(const Ezsignformfieldgroup_RequestCompound &obj_ezsignformfieldgroup) {
    m_obj_ezsignformfieldgroup = obj_ezsignformfieldgroup;
    m_obj_ezsignformfieldgroup_isSet = true;
}

bool Ezsignformfieldgroup_editObject_v1_Request::is_obj_ezsignformfieldgroup_Set() const{
    return m_obj_ezsignformfieldgroup_isSet;
}

bool Ezsignformfieldgroup_editObject_v1_Request::is_obj_ezsignformfieldgroup_Valid() const{
    return m_obj_ezsignformfieldgroup_isValid;
}

bool Ezsignformfieldgroup_editObject_v1_Request::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_obj_ezsignformfieldgroup.isSet()) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool Ezsignformfieldgroup_editObject_v1_Request::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_obj_ezsignformfieldgroup_isValid && true;
}

} // namespace Ezmaxapi
