/**
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.2.1
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "Field_eEzsigntemplatepublicLimittype.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "Helpers.h"

namespace Ezmaxapi {

Field_eEzsigntemplatepublicLimittype::Field_eEzsigntemplatepublicLimittype(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

Field_eEzsigntemplatepublicLimittype::Field_eEzsigntemplatepublicLimittype() {
    this->initializeModel();
}

Field_eEzsigntemplatepublicLimittype::~Field_eEzsigntemplatepublicLimittype() {}

void Field_eEzsigntemplatepublicLimittype::initializeModel() {

    m_value_isSet = false;
    m_value_isValid = false;
    m_value = eField_eEzsigntemplatepublicLimittype::INVALID_VALUE_OPENAPI_GENERATED;
}

void Field_eEzsigntemplatepublicLimittype::fromJson(QString jsonString) {
    
    if ( jsonString.compare("Hour", Qt::CaseInsensitive) == 0) {
        m_value = eField_eEzsigntemplatepublicLimittype::HOUR;
        m_value_isSet = m_value_isValid = true;
    }
    else if ( jsonString.compare("Day", Qt::CaseInsensitive) == 0) {
        m_value = eField_eEzsigntemplatepublicLimittype::DAY;
        m_value_isSet = m_value_isValid = true;
    }
    else if ( jsonString.compare("Month", Qt::CaseInsensitive) == 0) {
        m_value = eField_eEzsigntemplatepublicLimittype::MONTH;
        m_value_isSet = m_value_isValid = true;
    }
    else if ( jsonString.compare("Total", Qt::CaseInsensitive) == 0) {
        m_value = eField_eEzsigntemplatepublicLimittype::TOTAL;
        m_value_isSet = m_value_isValid = true;
    }
}

void Field_eEzsigntemplatepublicLimittype::fromJsonValue(QJsonValue json) {
fromJson(json.toString());
}

QString Field_eEzsigntemplatepublicLimittype::asJson() const {
    
    QString val;
    switch (m_value){
        case eField_eEzsigntemplatepublicLimittype::HOUR:
            val = "Hour";
            break;
        case eField_eEzsigntemplatepublicLimittype::DAY:
            val = "Day";
            break;
        case eField_eEzsigntemplatepublicLimittype::MONTH:
            val = "Month";
            break;
        case eField_eEzsigntemplatepublicLimittype::TOTAL:
            val = "Total";
            break;
        default:
            break;
    }
    return val;
}

QJsonValue Field_eEzsigntemplatepublicLimittype::asJsonValue() const {
    
    return QJsonValue(asJson());
}


Field_eEzsigntemplatepublicLimittype::eField_eEzsigntemplatepublicLimittype Field_eEzsigntemplatepublicLimittype::getValue() const {
    return m_value;
}

void Field_eEzsigntemplatepublicLimittype::setValue(const Field_eEzsigntemplatepublicLimittype::eField_eEzsigntemplatepublicLimittype& value){
    m_value = value;
    m_value_isSet = true;
}
bool Field_eEzsigntemplatepublicLimittype::isSet() const {
    
    return m_value_isSet;
}

bool Field_eEzsigntemplatepublicLimittype::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_value_isValid;
}

} // namespace Ezmaxapi
