/**
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.3.3
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Field_eInscriptionRemunerationinscriptorsellertype.h
 *
 * The type of remuneration for inscriptor and seller of the Inscription
 */

#ifndef Field_eInscriptionRemunerationinscriptorsellertype_H
#define Field_eInscriptionRemunerationinscriptorsellertype_H

#include <QJsonObject>


#include "Enum.h"
#include "Object.h"

namespace Ezmaxapi {

class Field_eInscriptionRemunerationinscriptorsellertype : public Enum {
public:
    Field_eInscriptionRemunerationinscriptorsellertype();
    Field_eInscriptionRemunerationinscriptorsellertype(const QString &json);
    ~Field_eInscriptionRemunerationinscriptorsellertype() override;

    QString asJson() const override;
    QJsonValue asJsonValue() const override;
    void fromJsonValue(QJsonValue json) override;
    void fromJson(const QString &jsonString) override;

    enum class eField_eInscriptionRemunerationinscriptorsellertype {
        INVALID_VALUE_OPENAPI_GENERATED = 0,
        PERCENTAGE, 
        DOLLARS
    };
    Field_eInscriptionRemunerationinscriptorsellertype::eField_eInscriptionRemunerationinscriptorsellertype getValue() const;
    void setValue(const Field_eInscriptionRemunerationinscriptorsellertype::eField_eInscriptionRemunerationinscriptorsellertype& value);
    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    eField_eInscriptionRemunerationinscriptorsellertype m_value;
    bool m_value_isSet;
    bool m_value_isValid;
};

} // namespace Ezmaxapi

Q_DECLARE_METATYPE(Ezmaxapi::Field_eInscriptionRemunerationinscriptorsellertype)

#endif // Field_eInscriptionRemunerationinscriptorsellertype_H
