/**
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.2.2
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Field_eEzsigntemplatedocumentpagerecognitionSection.h
 *
 * The section of the Ezsigntemplatedocumentpagerecognition
 */

#ifndef Field_eEzsigntemplatedocumentpagerecognitionSection_H
#define Field_eEzsigntemplatedocumentpagerecognitionSection_H

#include <QJsonObject>


#include "Enum.h"
#include "Object.h"

namespace Ezmaxapi {

class Field_eEzsigntemplatedocumentpagerecognitionSection : public Enum {
public:
    Field_eEzsigntemplatedocumentpagerecognitionSection();
    Field_eEzsigntemplatedocumentpagerecognitionSection(QString json);
    ~Field_eEzsigntemplatedocumentpagerecognitionSection() override;

    QString asJson() const override;
    QJsonValue asJsonValue() const override;
    void fromJsonValue(QJsonValue json) override;
    void fromJson(QString jsonString) override;

    enum class eField_eEzsigntemplatedocumentpagerecognitionSection {
        INVALID_VALUE_OPENAPI_GENERATED = 0,
        FIRSTLINE, 
        LASTLINE, 
        PAGE, 
        REGION
    };
    Field_eEzsigntemplatedocumentpagerecognitionSection::eField_eEzsigntemplatedocumentpagerecognitionSection getValue() const;
    void setValue(const Field_eEzsigntemplatedocumentpagerecognitionSection::eField_eEzsigntemplatedocumentpagerecognitionSection& value);
    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    eField_eEzsigntemplatedocumentpagerecognitionSection m_value;
    bool m_value_isSet;
    bool m_value_isValid;
};

} // namespace Ezmaxapi

Q_DECLARE_METATYPE(Ezmaxapi::Field_eEzsigntemplatedocumentpagerecognitionSection)

#endif // Field_eEzsigntemplatedocumentpagerecognitionSection_H
