/**
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.2.1
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Field_eAttachmentVerified.h
 *
 * The verified of the Attachment
 */

#ifndef Field_eAttachmentVerified_H
#define Field_eAttachmentVerified_H

#include <QJsonObject>


#include "Enum.h"
#include "Object.h"

namespace Ezmaxapi {

class Field_eAttachmentVerified : public Enum {
public:
    Field_eAttachmentVerified();
    Field_eAttachmentVerified(QString json);
    ~Field_eAttachmentVerified() override;

    QString asJson() const override;
    QJsonValue asJsonValue() const override;
    void fromJsonValue(QJsonValue json) override;
    void fromJson(QString jsonString) override;

    enum class eField_eAttachmentVerified {
        INVALID_VALUE_OPENAPI_GENERATED = 0,
        NO, 
        YES, 
        REJECTED
    };
    Field_eAttachmentVerified::eField_eAttachmentVerified getValue() const;
    void setValue(const Field_eAttachmentVerified::eField_eAttachmentVerified& value);
    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    eField_eAttachmentVerified m_value;
    bool m_value_isSet;
    bool m_value_isValid;
};

} // namespace Ezmaxapi

Q_DECLARE_METATYPE(Ezmaxapi::Field_eAttachmentVerified)

#endif // Field_eAttachmentVerified_H
