/**
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "Multilingual_EzsignsigningreasonDescription.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "Helpers.h"

namespace Ezmaxapi {

Multilingual_EzsignsigningreasonDescription::Multilingual_EzsignsigningreasonDescription(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

Multilingual_EzsignsigningreasonDescription::Multilingual_EzsignsigningreasonDescription() {
    this->initializeModel();
}

Multilingual_EzsignsigningreasonDescription::~Multilingual_EzsignsigningreasonDescription() {}

void Multilingual_EzsignsigningreasonDescription::initializeModel() {

    m_s_ezsignsigningreason_description1_isSet = false;
    m_s_ezsignsigningreason_description1_isValid = false;

    m_s_ezsignsigningreason_description2_isSet = false;
    m_s_ezsignsigningreason_description2_isValid = false;
}

void Multilingual_EzsignsigningreasonDescription::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void Multilingual_EzsignsigningreasonDescription::fromJsonObject(QJsonObject json) {

    m_s_ezsignsigningreason_description1_isValid = ::Ezmaxapi::fromJsonValue(m_s_ezsignsigningreason_description1, json[QString("sEzsignsigningreasonDescription1")]);
    m_s_ezsignsigningreason_description1_isSet = !json[QString("sEzsignsigningreasonDescription1")].isNull() && m_s_ezsignsigningreason_description1_isValid;

    m_s_ezsignsigningreason_description2_isValid = ::Ezmaxapi::fromJsonValue(m_s_ezsignsigningreason_description2, json[QString("sEzsignsigningreasonDescription2")]);
    m_s_ezsignsigningreason_description2_isSet = !json[QString("sEzsignsigningreasonDescription2")].isNull() && m_s_ezsignsigningreason_description2_isValid;
}

QString Multilingual_EzsignsigningreasonDescription::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject Multilingual_EzsignsigningreasonDescription::asJsonObject() const {
    QJsonObject obj;
    if (m_s_ezsignsigningreason_description1_isSet) {
        obj.insert(QString("sEzsignsigningreasonDescription1"), ::Ezmaxapi::toJsonValue(m_s_ezsignsigningreason_description1));
    }
    if (m_s_ezsignsigningreason_description2_isSet) {
        obj.insert(QString("sEzsignsigningreasonDescription2"), ::Ezmaxapi::toJsonValue(m_s_ezsignsigningreason_description2));
    }
    return obj;
}

QString Multilingual_EzsignsigningreasonDescription::getSEzsignsigningreasonDescription1() const {
    return m_s_ezsignsigningreason_description1;
}
void Multilingual_EzsignsigningreasonDescription::setSEzsignsigningreasonDescription1(const QString &s_ezsignsigningreason_description1) {
    m_s_ezsignsigningreason_description1 = s_ezsignsigningreason_description1;
    m_s_ezsignsigningreason_description1_isSet = true;
}

bool Multilingual_EzsignsigningreasonDescription::is_s_ezsignsigningreason_description1_Set() const{
    return m_s_ezsignsigningreason_description1_isSet;
}

bool Multilingual_EzsignsigningreasonDescription::is_s_ezsignsigningreason_description1_Valid() const{
    return m_s_ezsignsigningreason_description1_isValid;
}

QString Multilingual_EzsignsigningreasonDescription::getSEzsignsigningreasonDescription2() const {
    return m_s_ezsignsigningreason_description2;
}
void Multilingual_EzsignsigningreasonDescription::setSEzsignsigningreasonDescription2(const QString &s_ezsignsigningreason_description2) {
    m_s_ezsignsigningreason_description2 = s_ezsignsigningreason_description2;
    m_s_ezsignsigningreason_description2_isSet = true;
}

bool Multilingual_EzsignsigningreasonDescription::is_s_ezsignsigningreason_description2_Set() const{
    return m_s_ezsignsigningreason_description2_isSet;
}

bool Multilingual_EzsignsigningreasonDescription::is_s_ezsignsigningreason_description2_Valid() const{
    return m_s_ezsignsigningreason_description2_isValid;
}

bool Multilingual_EzsignsigningreasonDescription::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_s_ezsignsigningreason_description1_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_s_ezsignsigningreason_description2_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool Multilingual_EzsignsigningreasonDescription::isValid() const {
    // only required properties are required for the object to be considered valid
    return true;
}

} // namespace Ezmaxapi
