/**
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAICustom_Ezsignformfield_Request.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAICustom_Ezsignformfield_Request::OAICustom_Ezsignformfield_Request(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAICustom_Ezsignformfield_Request::OAICustom_Ezsignformfield_Request() {
    this->initializeModel();
}

OAICustom_Ezsignformfield_Request::~OAICustom_Ezsignformfield_Request() {}

void OAICustom_Ezsignformfield_Request::initializeModel() {

    m_pki_ezsignformfield_id_isSet = false;
    m_pki_ezsignformfield_id_isValid = false;

    m_s_ezsignformfield_label_isSet = false;
    m_s_ezsignformfield_label_isValid = false;

    m_b_ezsignformfield_selected_isSet = false;
    m_b_ezsignformfield_selected_isValid = false;

    m_s_ezsignformfield_enteredvalue_isSet = false;
    m_s_ezsignformfield_enteredvalue_isValid = false;
}

void OAICustom_Ezsignformfield_Request::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAICustom_Ezsignformfield_Request::fromJsonObject(QJsonObject json) {

    m_pki_ezsignformfield_id_isValid = ::OpenAPI::fromJsonValue(m_pki_ezsignformfield_id, json[QString("pkiEzsignformfieldID")]);
    m_pki_ezsignformfield_id_isSet = !json[QString("pkiEzsignformfieldID")].isNull() && m_pki_ezsignformfield_id_isValid;

    m_s_ezsignformfield_label_isValid = ::OpenAPI::fromJsonValue(m_s_ezsignformfield_label, json[QString("sEzsignformfieldLabel")]);
    m_s_ezsignformfield_label_isSet = !json[QString("sEzsignformfieldLabel")].isNull() && m_s_ezsignformfield_label_isValid;

    m_b_ezsignformfield_selected_isValid = ::OpenAPI::fromJsonValue(m_b_ezsignformfield_selected, json[QString("bEzsignformfieldSelected")]);
    m_b_ezsignformfield_selected_isSet = !json[QString("bEzsignformfieldSelected")].isNull() && m_b_ezsignformfield_selected_isValid;

    m_s_ezsignformfield_enteredvalue_isValid = ::OpenAPI::fromJsonValue(m_s_ezsignformfield_enteredvalue, json[QString("sEzsignformfieldEnteredvalue")]);
    m_s_ezsignformfield_enteredvalue_isSet = !json[QString("sEzsignformfieldEnteredvalue")].isNull() && m_s_ezsignformfield_enteredvalue_isValid;
}

QString OAICustom_Ezsignformfield_Request::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAICustom_Ezsignformfield_Request::asJsonObject() const {
    QJsonObject obj;
    if (m_pki_ezsignformfield_id_isSet) {
        obj.insert(QString("pkiEzsignformfieldID"), ::OpenAPI::toJsonValue(m_pki_ezsignformfield_id));
    }
    if (m_s_ezsignformfield_label_isSet) {
        obj.insert(QString("sEzsignformfieldLabel"), ::OpenAPI::toJsonValue(m_s_ezsignformfield_label));
    }
    if (m_b_ezsignformfield_selected_isSet) {
        obj.insert(QString("bEzsignformfieldSelected"), ::OpenAPI::toJsonValue(m_b_ezsignformfield_selected));
    }
    if (m_s_ezsignformfield_enteredvalue_isSet) {
        obj.insert(QString("sEzsignformfieldEnteredvalue"), ::OpenAPI::toJsonValue(m_s_ezsignformfield_enteredvalue));
    }
    return obj;
}

qint32 OAICustom_Ezsignformfield_Request::getPkiEzsignformfieldId() const {
    return m_pki_ezsignformfield_id;
}
void OAICustom_Ezsignformfield_Request::setPkiEzsignformfieldId(const qint32 &pki_ezsignformfield_id) {
    m_pki_ezsignformfield_id = pki_ezsignformfield_id;
    m_pki_ezsignformfield_id_isSet = true;
}

bool OAICustom_Ezsignformfield_Request::is_pki_ezsignformfield_id_Set() const{
    return m_pki_ezsignformfield_id_isSet;
}

bool OAICustom_Ezsignformfield_Request::is_pki_ezsignformfield_id_Valid() const{
    return m_pki_ezsignformfield_id_isValid;
}

QString OAICustom_Ezsignformfield_Request::getSEzsignformfieldLabel() const {
    return m_s_ezsignformfield_label;
}
void OAICustom_Ezsignformfield_Request::setSEzsignformfieldLabel(const QString &s_ezsignformfield_label) {
    m_s_ezsignformfield_label = s_ezsignformfield_label;
    m_s_ezsignformfield_label_isSet = true;
}

bool OAICustom_Ezsignformfield_Request::is_s_ezsignformfield_label_Set() const{
    return m_s_ezsignformfield_label_isSet;
}

bool OAICustom_Ezsignformfield_Request::is_s_ezsignformfield_label_Valid() const{
    return m_s_ezsignformfield_label_isValid;
}

bool OAICustom_Ezsignformfield_Request::isBEzsignformfieldSelected() const {
    return m_b_ezsignformfield_selected;
}
void OAICustom_Ezsignformfield_Request::setBEzsignformfieldSelected(const bool &b_ezsignformfield_selected) {
    m_b_ezsignformfield_selected = b_ezsignformfield_selected;
    m_b_ezsignformfield_selected_isSet = true;
}

bool OAICustom_Ezsignformfield_Request::is_b_ezsignformfield_selected_Set() const{
    return m_b_ezsignformfield_selected_isSet;
}

bool OAICustom_Ezsignformfield_Request::is_b_ezsignformfield_selected_Valid() const{
    return m_b_ezsignformfield_selected_isValid;
}

QString OAICustom_Ezsignformfield_Request::getSEzsignformfieldEnteredvalue() const {
    return m_s_ezsignformfield_enteredvalue;
}
void OAICustom_Ezsignformfield_Request::setSEzsignformfieldEnteredvalue(const QString &s_ezsignformfield_enteredvalue) {
    m_s_ezsignformfield_enteredvalue = s_ezsignformfield_enteredvalue;
    m_s_ezsignformfield_enteredvalue_isSet = true;
}

bool OAICustom_Ezsignformfield_Request::is_s_ezsignformfield_enteredvalue_Set() const{
    return m_s_ezsignformfield_enteredvalue_isSet;
}

bool OAICustom_Ezsignformfield_Request::is_s_ezsignformfield_enteredvalue_Valid() const{
    return m_s_ezsignformfield_enteredvalue_isValid;
}

bool OAICustom_Ezsignformfield_Request::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_pki_ezsignformfield_id_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_s_ezsignformfield_label_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_b_ezsignformfield_selected_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_s_ezsignformfield_enteredvalue_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAICustom_Ezsignformfield_Request::isValid() const {
    // only required properties are required for the object to be considered valid
    return true;
}

} // namespace OpenAPI
