/**
 * eZmax API Definition
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.1.5
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIField_eActivesessionSessiontype.h
 *
 * The Type of session for the Activesession
 */

#ifndef OAIField_eActivesessionSessiontype_H
#define OAIField_eActivesessionSessiontype_H

#include <QJsonObject>


#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAIField_eActivesessionSessiontype : public OAIEnum {
public:
    OAIField_eActivesessionSessiontype();
    OAIField_eActivesessionSessiontype(QString json);
    ~OAIField_eActivesessionSessiontype() override;

    QString asJson() const override;
    QJsonValue asJsonValue() const override;
    void fromJsonValue(QJsonValue json) override;
    void fromJson(QString jsonString) override;

    enum class eOAIField_eActivesessionSessiontype {
        INVALID_VALUE_OPENAPI_GENERATED = 0,
        NORMAL
    };
    OAIField_eActivesessionSessiontype::eOAIField_eActivesessionSessiontype getValue() const;
    void setValue(const OAIField_eActivesessionSessiontype::eOAIField_eActivesessionSessiontype& value);
    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    eOAIField_eActivesessionSessiontype m_value;
    bool m_value_isSet;
    bool m_value_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIField_eActivesessionSessiontype)

#endif // OAIField_eActivesessionSessiontype_H
