/**
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.1.18
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIUserstaged_getList_v1_Response_mPayload_allOf.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAIUserstaged_getList_v1_Response_mPayload_allOf::OAIUserstaged_getList_v1_Response_mPayload_allOf(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAIUserstaged_getList_v1_Response_mPayload_allOf::OAIUserstaged_getList_v1_Response_mPayload_allOf() {
    this->initializeModel();
}

OAIUserstaged_getList_v1_Response_mPayload_allOf::~OAIUserstaged_getList_v1_Response_mPayload_allOf() {}

void OAIUserstaged_getList_v1_Response_mPayload_allOf::initializeModel() {

    m_a_obj_userstaged_isSet = false;
    m_a_obj_userstaged_isValid = false;
}

void OAIUserstaged_getList_v1_Response_mPayload_allOf::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIUserstaged_getList_v1_Response_mPayload_allOf::fromJsonObject(QJsonObject json) {

    m_a_obj_userstaged_isValid = ::OpenAPI::fromJsonValue(a_obj_userstaged, json[QString("a_objUserstaged")]);
    m_a_obj_userstaged_isSet = !json[QString("a_objUserstaged")].isNull() && m_a_obj_userstaged_isValid;
}

QString OAIUserstaged_getList_v1_Response_mPayload_allOf::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIUserstaged_getList_v1_Response_mPayload_allOf::asJsonObject() const {
    QJsonObject obj;
    if (a_obj_userstaged.size() > 0) {
        obj.insert(QString("a_objUserstaged"), ::OpenAPI::toJsonValue(a_obj_userstaged));
    }
    return obj;
}

QList<OAIUserstaged_ListElement> OAIUserstaged_getList_v1_Response_mPayload_allOf::getAObjUserstaged() const {
    return a_obj_userstaged;
}
void OAIUserstaged_getList_v1_Response_mPayload_allOf::setAObjUserstaged(const QList<OAIUserstaged_ListElement> &a_obj_userstaged) {
    this->a_obj_userstaged = a_obj_userstaged;
    this->m_a_obj_userstaged_isSet = true;
}

bool OAIUserstaged_getList_v1_Response_mPayload_allOf::is_a_obj_userstaged_Set() const{
    return m_a_obj_userstaged_isSet;
}

bool OAIUserstaged_getList_v1_Response_mPayload_allOf::is_a_obj_userstaged_Valid() const{
    return m_a_obj_userstaged_isValid;
}

bool OAIUserstaged_getList_v1_Response_mPayload_allOf::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (a_obj_userstaged.size() > 0) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIUserstaged_getList_v1_Response_mPayload_allOf::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_a_obj_userstaged_isValid && true;
}

} // namespace OpenAPI
