/**
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.3.4
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "ObjectDisclosureApi.h"
#include "ServerConfiguration.h"
#include <QJsonArray>
#include <QJsonDocument>

namespace Ezmaxapi {

ObjectDisclosureApi::ObjectDisclosureApi(const int timeOut)
    : _timeOut(timeOut),
      _manager(nullptr),
      _isResponseCompressionEnabled(false),
      _isRequestCompressionEnabled(false) {
    initializeServerConfigs();
}

ObjectDisclosureApi::~ObjectDisclosureApi() {
}

void ObjectDisclosureApi::initializeServerConfigs() {
    //Default server
    QList<ServerConfiguration> defaultConf = QList<ServerConfiguration>();
    //varying endpoint server
    defaultConf.append(ServerConfiguration(
    QUrl("https://{sInfrastructureenvironmenttypeDescription}.api.appcluster01.{sInfrastructureregionCode}.ezmax.com/rest"),
    "The server endpoint where to send your region specific API requests.",
    QMap<QString, ServerVariable>{ 
    {"sInfrastructureenvironmenttypeDescription", ServerVariable("The environment on on which to call the API. Should always be "prod" unless instructed otherwise by support.","prod",
    QSet<QString>{ {"iso"},{"prod"},{"stg"},{"qa"},{"dev"} })},
    
    {"sInfrastructureregionCode", ServerVariable("The region where your services are hosted.","ca-central-1",
    QSet<QString>{ {"ca-central-1"} })}, }));
    
    defaultConf.append(ServerConfiguration(
    QUrl("https://{sInfrastructureenvironmenttypeDescription}.api.global.ezmax.com"),
    "The server endpoint where to send your global API requests.",
    QMap<QString, ServerVariable>{ 
    {"sInfrastructureenvironmenttypeDescription", ServerVariable("The environment on on which to call the API. Should always be "prod" unless instructed otherwise by support.","prod",
    QSet<QString>{ {"prod"},{"dev"} })}, }));
    
    defaultConf.append(ServerConfiguration(
    QUrl("wss://ws.{sInfrastructureregionCode}.ezmax.com/{sInfrastructureenvironmenttypeDescription}"),
    "The server endpoint where to send your websocket requests.",
    QMap<QString, ServerVariable>{ 
    {"sInfrastructureenvironmenttypeDescription", ServerVariable("The environment on on which to call the API. Should always be "prod" unless instructed otherwise by support.","prod",
    QSet<QString>{ {"iso"},{"prod"},{"stg"},{"qa"},{"dev"} })},
    
    {"sInfrastructureregionCode", ServerVariable("The region where your services are hosted.","ca-central-1",
    QSet<QString>{ {"ca-central-1"} })}, }));
    
    _serverConfigs.insert("disclosureBatchDownloadV1", defaultConf);
    _serverIndices.insert("disclosureBatchDownloadV1", 0);
    _serverConfigs.insert("disclosureGetAttachmentsV1", defaultConf);
    _serverIndices.insert("disclosureGetAttachmentsV1", 0);
    _serverConfigs.insert("disclosureImportIntoEDMV1", defaultConf);
    _serverIndices.insert("disclosureImportIntoEDMV1", 0);
}

/**
 * returns 0 on success and -1, -2 or -3 on failure.
 * -1 when the variable does not exist and -2 if the value is not defined in the enum and -3 if the operation or server index is not found
 */
int ObjectDisclosureApi::setDefaultServerValue(int serverIndex, const QString &operation, const QString &variable, const QString &value) {
    auto it = _serverConfigs.find(operation);
    if (it != _serverConfigs.end() && serverIndex < it.value().size()) {
      return _serverConfigs[operation][serverIndex].setDefaultValue(variable,value);
    }
    return -3;
}

/**
 * Sets the server index.
 * @param operation The id to the target operation.
 * @param serverIndex The server index.
 */
void ObjectDisclosureApi::setServerIndex(const QString &operation, int serverIndex) {
    if (_serverIndices.contains(operation) && serverIndex < _serverConfigs.find(operation).value().size()) {
        _serverIndices[operation] = serverIndex;
    }
}

void ObjectDisclosureApi::setServerIndex(int serverIndex) {
    for (auto keyIt = _serverIndices.keyBegin(); keyIt != _serverIndices.keyEnd(); keyIt++) {
        setServerIndex(*keyIt, serverIndex);
    }
}

void ObjectDisclosureApi::setApiKey(const QString &apiKeyName, const QString &apiKey) {
    _apiKeys.insert(apiKeyName, apiKey);
}

void ObjectDisclosureApi::setBearerToken(const QString &token) {
    _bearerToken = token;
}

void ObjectDisclosureApi::setUsername(const QString &username) {
    _username = username;
}

void ObjectDisclosureApi::setPassword(const QString &password) {
    _password = password;
}


void ObjectDisclosureApi::setTimeOut(const int timeOut) {
    _timeOut = timeOut;
}

void ObjectDisclosureApi::setWorkingDirectory(const QString &path) {
    _workingDirectory = path;
}

void ObjectDisclosureApi::setNetworkAccessManager(QNetworkAccessManager* manager) {
    _manager = manager;
}

/**
 * Appends a new ServerConfiguration to the config map for a specific operation.
 * @param operation The id to the target operation.
 * @param url A string that contains the URL of the server
 * @param description A String that describes the server
 * @param variables A map between a variable name and its value. The value is used for substitution in the server's URL template.
 * returns the index of the new server config on success and -1 if the operation is not found
 */
int ObjectDisclosureApi::addServerConfiguration(const QString &operation, const QUrl &url, const QString &description, const QMap<QString, ServerVariable> &variables) {
    if (_serverConfigs.contains(operation)) {
        _serverConfigs[operation].append(ServerConfiguration(
                    url,
                    description,
                    variables));
        return _serverConfigs[operation].size()-1;
    } else {
        return -1;
    }
}

/**
 * Appends a new ServerConfiguration to the config map for a all operations and sets the index to that server.
 * @param url A string that contains the URL of the server
 * @param description A String that describes the server
 * @param variables A map between a variable name and its value. The value is used for substitution in the server's URL template.
 */
void ObjectDisclosureApi::setNewServerForAllOperations(const QUrl &url, const QString &description, const QMap<QString, ServerVariable> &variables) {
    for (auto keyIt = _serverIndices.keyBegin(); keyIt != _serverIndices.keyEnd(); keyIt++) {
        setServerIndex(*keyIt, addServerConfiguration(*keyIt, url, description, variables));
    }
}

/**
 * Appends a new ServerConfiguration to the config map for an operations and sets the index to that server.
 * @param URL A string that contains the URL of the server
 * @param description A String that describes the server
 * @param variables A map between a variable name and its value. The value is used for substitution in the server's URL template.
 */
void ObjectDisclosureApi::setNewServer(const QString &operation, const QUrl &url, const QString &description, const QMap<QString, ServerVariable> &variables) {
    setServerIndex(operation, addServerConfiguration(operation, url, description, variables));
}

void ObjectDisclosureApi::addHeaders(const QString &key, const QString &value) {
    _defaultHeaders.insert(key, value);
}

void ObjectDisclosureApi::enableRequestCompression() {
    _isRequestCompressionEnabled = true;
}

void ObjectDisclosureApi::enableResponseCompression() {
    _isResponseCompressionEnabled = true;
}

void ObjectDisclosureApi::abortRequests() {
    Q_EMIT abortRequestsSignal();
}

QString ObjectDisclosureApi::getParamStylePrefix(const QString &style) {
    if (style == "matrix") {
        return ";";
    } else if (style == "label") {
        return ".";
    } else if (style == "form") {
        return "&";
    } else if (style == "simple") {
        return "";
    } else if (style == "spaceDelimited") {
        return "&";
    } else if (style == "pipeDelimited") {
        return "&";
    } else {
        return "none";
    }
}

QString ObjectDisclosureApi::getParamStyleSuffix(const QString &style) {
    if (style == "matrix") {
        return "=";
    } else if (style == "label") {
        return "";
    } else if (style == "form") {
        return "=";
    } else if (style == "simple") {
        return "";
    } else if (style == "spaceDelimited") {
        return "=";
    } else if (style == "pipeDelimited") {
        return "=";
    } else {
        return "none";
    }
}

QString ObjectDisclosureApi::getParamStyleDelimiter(const QString &style, const QString &name, bool isExplode) {

    if (style == "matrix") {
        return (isExplode) ? ";" + name + "=" : ",";

    } else if (style == "label") {
        return (isExplode) ? "." : ",";

    } else if (style == "form") {
        return (isExplode) ? "&" + name + "=" : ",";

    } else if (style == "simple") {
        return ",";
    } else if (style == "spaceDelimited") {
        return (isExplode) ? "&" + name + "=" : " ";

    } else if (style == "pipeDelimited") {
        return (isExplode) ? "&" + name + "=" : "|";

    } else if (style == "deepObject") {
        return (isExplode) ? "&" : "none";

    } else {
        return "none";
    }
}

void ObjectDisclosureApi::disclosureBatchDownloadV1(const qint32 &pki_disclosure_id, const Disclosure_batchDownload_v1_Request &disclosure_batch_download_v1_request) {
    QString fullPath = QString(_serverConfigs["disclosureBatchDownloadV1"][_serverIndices.value("disclosureBatchDownloadV1")].URL()+"/1/object/disclosure/{pkiDisclosureID}/batchDownload");
    
    if (_apiKeys.contains("Authorization")) {
        addHeaders("Authorization",_apiKeys.find("Authorization").value());
    }
    
    
    {
        QString pki_disclosure_idPathParam("{");
        pki_disclosure_idPathParam.append("pkiDisclosureID").append("}");
        QString pathPrefix, pathSuffix, pathDelimiter;
        QString pathStyle = "simple";
        if (pathStyle == "")
            pathStyle = "simple";
        pathPrefix = getParamStylePrefix(pathStyle);
        pathSuffix = getParamStyleSuffix(pathStyle);
        pathDelimiter = getParamStyleDelimiter(pathStyle, "pkiDisclosureID", false);
        QString paramString = (pathStyle == "matrix") ? pathPrefix+"pkiDisclosureID"+pathSuffix : pathPrefix;
        fullPath.replace(pki_disclosure_idPathParam, paramString+QUrl::toPercentEncoding(::Ezmaxapi::toStringValue(pki_disclosure_id)));
    }
    HttpRequestWorker *worker = new HttpRequestWorker(this, _manager);
    worker->setTimeOut(_timeOut);
    worker->setWorkingDirectory(_workingDirectory);
    HttpRequestInput input(fullPath, "POST");

    {

        
        QByteArray output = disclosure_batch_download_v1_request.asJson().toUtf8();
        input.request_body.append(output);
    }
    for (auto keyValueIt = _defaultHeaders.keyValueBegin(); keyValueIt != _defaultHeaders.keyValueEnd(); keyValueIt++) {
        input.headers.insert(keyValueIt->first, keyValueIt->second);
    }


    connect(worker, &HttpRequestWorker::on_execution_finished, this, &ObjectDisclosureApi::disclosureBatchDownloadV1Callback);
    connect(this, &ObjectDisclosureApi::abortRequestsSignal, worker, &QObject::deleteLater);
    connect(worker, &QObject::destroyed, this, [this] {
        if (findChildren<HttpRequestWorker*>().count() == 0) {
            Q_EMIT allPendingRequestsCompleted();
        }
    });

    worker->execute(&input);
}

void ObjectDisclosureApi::disclosureBatchDownloadV1Callback(HttpRequestWorker *worker) {
    QString error_str = worker->error_str;
    QNetworkReply::NetworkError error_type = worker->error_type;

    if (worker->error_type != QNetworkReply::NoError) {
        error_str = QString("%1, %2").arg(worker->error_str, QString(worker->response));
    }
    HttpFileElement output = worker->getHttpFileElement();
    worker->deleteLater();

    if (worker->error_type == QNetworkReply::NoError) {
        Q_EMIT disclosureBatchDownloadV1Signal(output);
        Q_EMIT disclosureBatchDownloadV1SignalFull(worker, output);
    } else {
        Q_EMIT disclosureBatchDownloadV1SignalError(output, error_type, error_str);
        Q_EMIT disclosureBatchDownloadV1SignalErrorFull(worker, error_type, error_str);
    }
}

void ObjectDisclosureApi::disclosureGetAttachmentsV1(const qint32 &pki_disclosure_id) {
    QString fullPath = QString(_serverConfigs["disclosureGetAttachmentsV1"][_serverIndices.value("disclosureGetAttachmentsV1")].URL()+"/1/object/disclosure/{pkiDisclosureID}/getAttachments");
    
    if (_apiKeys.contains("Authorization")) {
        addHeaders("Authorization",_apiKeys.find("Authorization").value());
    }
    
    
    {
        QString pki_disclosure_idPathParam("{");
        pki_disclosure_idPathParam.append("pkiDisclosureID").append("}");
        QString pathPrefix, pathSuffix, pathDelimiter;
        QString pathStyle = "simple";
        if (pathStyle == "")
            pathStyle = "simple";
        pathPrefix = getParamStylePrefix(pathStyle);
        pathSuffix = getParamStyleSuffix(pathStyle);
        pathDelimiter = getParamStyleDelimiter(pathStyle, "pkiDisclosureID", false);
        QString paramString = (pathStyle == "matrix") ? pathPrefix+"pkiDisclosureID"+pathSuffix : pathPrefix;
        fullPath.replace(pki_disclosure_idPathParam, paramString+QUrl::toPercentEncoding(::Ezmaxapi::toStringValue(pki_disclosure_id)));
    }
    HttpRequestWorker *worker = new HttpRequestWorker(this, _manager);
    worker->setTimeOut(_timeOut);
    worker->setWorkingDirectory(_workingDirectory);
    HttpRequestInput input(fullPath, "GET");


    for (auto keyValueIt = _defaultHeaders.keyValueBegin(); keyValueIt != _defaultHeaders.keyValueEnd(); keyValueIt++) {
        input.headers.insert(keyValueIt->first, keyValueIt->second);
    }


    connect(worker, &HttpRequestWorker::on_execution_finished, this, &ObjectDisclosureApi::disclosureGetAttachmentsV1Callback);
    connect(this, &ObjectDisclosureApi::abortRequestsSignal, worker, &QObject::deleteLater);
    connect(worker, &QObject::destroyed, this, [this] {
        if (findChildren<HttpRequestWorker*>().count() == 0) {
            Q_EMIT allPendingRequestsCompleted();
        }
    });

    worker->execute(&input);
}

void ObjectDisclosureApi::disclosureGetAttachmentsV1Callback(HttpRequestWorker *worker) {
    QString error_str = worker->error_str;
    QNetworkReply::NetworkError error_type = worker->error_type;

    if (worker->error_type != QNetworkReply::NoError) {
        error_str = QString("%1, %2").arg(worker->error_str, QString(worker->response));
    }
    Disclosure_getAttachments_v1_Response output(QString(worker->response));
    worker->deleteLater();

    if (worker->error_type == QNetworkReply::NoError) {
        Q_EMIT disclosureGetAttachmentsV1Signal(output);
        Q_EMIT disclosureGetAttachmentsV1SignalFull(worker, output);
    } else {
        Q_EMIT disclosureGetAttachmentsV1SignalError(output, error_type, error_str);
        Q_EMIT disclosureGetAttachmentsV1SignalErrorFull(worker, error_type, error_str);
    }
}

void ObjectDisclosureApi::disclosureImportIntoEDMV1(const qint32 &pki_disclosure_id, const Disclosure_importIntoEDM_v1_Request &disclosure_import_into_edm_v1_request) {
    QString fullPath = QString(_serverConfigs["disclosureImportIntoEDMV1"][_serverIndices.value("disclosureImportIntoEDMV1")].URL()+"/1/object/disclosure/{pkiDisclosureID}/importIntoEDM");
    
    if (_apiKeys.contains("Authorization")) {
        addHeaders("Authorization",_apiKeys.find("Authorization").value());
    }
    
    
    {
        QString pki_disclosure_idPathParam("{");
        pki_disclosure_idPathParam.append("pkiDisclosureID").append("}");
        QString pathPrefix, pathSuffix, pathDelimiter;
        QString pathStyle = "simple";
        if (pathStyle == "")
            pathStyle = "simple";
        pathPrefix = getParamStylePrefix(pathStyle);
        pathSuffix = getParamStyleSuffix(pathStyle);
        pathDelimiter = getParamStyleDelimiter(pathStyle, "pkiDisclosureID", false);
        QString paramString = (pathStyle == "matrix") ? pathPrefix+"pkiDisclosureID"+pathSuffix : pathPrefix;
        fullPath.replace(pki_disclosure_idPathParam, paramString+QUrl::toPercentEncoding(::Ezmaxapi::toStringValue(pki_disclosure_id)));
    }
    HttpRequestWorker *worker = new HttpRequestWorker(this, _manager);
    worker->setTimeOut(_timeOut);
    worker->setWorkingDirectory(_workingDirectory);
    HttpRequestInput input(fullPath, "POST");

    {

        
        QByteArray output = disclosure_import_into_edm_v1_request.asJson().toUtf8();
        input.request_body.append(output);
    }
    for (auto keyValueIt = _defaultHeaders.keyValueBegin(); keyValueIt != _defaultHeaders.keyValueEnd(); keyValueIt++) {
        input.headers.insert(keyValueIt->first, keyValueIt->second);
    }


    connect(worker, &HttpRequestWorker::on_execution_finished, this, &ObjectDisclosureApi::disclosureImportIntoEDMV1Callback);
    connect(this, &ObjectDisclosureApi::abortRequestsSignal, worker, &QObject::deleteLater);
    connect(worker, &QObject::destroyed, this, [this] {
        if (findChildren<HttpRequestWorker*>().count() == 0) {
            Q_EMIT allPendingRequestsCompleted();
        }
    });

    worker->execute(&input);
}

void ObjectDisclosureApi::disclosureImportIntoEDMV1Callback(HttpRequestWorker *worker) {
    QString error_str = worker->error_str;
    QNetworkReply::NetworkError error_type = worker->error_type;

    if (worker->error_type != QNetworkReply::NoError) {
        error_str = QString("%1, %2").arg(worker->error_str, QString(worker->response));
    }
    Disclosure_importIntoEDM_v1_Response output(QString(worker->response));
    worker->deleteLater();

    if (worker->error_type == QNetworkReply::NoError) {
        Q_EMIT disclosureImportIntoEDMV1Signal(output);
        Q_EMIT disclosureImportIntoEDMV1SignalFull(worker, output);
    } else {
        Q_EMIT disclosureImportIntoEDMV1SignalError(output, error_type, error_str);
        Q_EMIT disclosureImportIntoEDMV1SignalErrorFull(worker, error_type, error_str);
    }
}

void ObjectDisclosureApi::tokenAvailable() {

    oauthToken token;
    switch (_OauthMethod) {
    case OauthMethod::ImplicitFlow:
        token = _implicitFlow.getToken(_latestScope.join(" "));
        if(token.isValid()){
            _latestInput.headers.insert("Authorization", "Bearer " + token.getToken());
            _latestWorker->execute(&_latestInput);
        }else{
            _implicitFlow.removeToken(_latestScope.join(" "));
            qDebug() << "Could not retrieve a valid token";
        }
        break;
    case OauthMethod::AuthorizationFlow:
        token = _authFlow.getToken(_latestScope.join(" "));
        if(token.isValid()){
            _latestInput.headers.insert("Authorization", "Bearer " + token.getToken());
            _latestWorker->execute(&_latestInput);
        }else{
            _authFlow.removeToken(_latestScope.join(" "));
            qDebug() << "Could not retrieve a valid token";
        }
        break;
    case OauthMethod::ClientCredentialsFlow:
        token = _credentialFlow.getToken(_latestScope.join(" "));
        if(token.isValid()){
            _latestInput.headers.insert("Authorization", "Bearer " + token.getToken());
            _latestWorker->execute(&_latestInput);
        }else{
            _credentialFlow.removeToken(_latestScope.join(" "));
            qDebug() << "Could not retrieve a valid token";
        }
        break;
    case OauthMethod::ResourceOwnerPasswordFlow:
        token = _passwordFlow.getToken(_latestScope.join(" "));
        if(token.isValid()){
            _latestInput.headers.insert("Authorization", "Bearer " + token.getToken());
            _latestWorker->execute(&_latestInput);
        }else{
            _credentialFlow.removeToken(_latestScope.join(" "));
            qDebug() << "Could not retrieve a valid token";
        }
        break;
    default:
        qDebug() << "No Oauth method set!";
        break;
    }
}
} // namespace Ezmaxapi
