/**
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.2.2
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "Variableexpense_getObject_v2_Response_mPayload.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "Helpers.h"

namespace Ezmaxapi {

Variableexpense_getObject_v2_Response_mPayload::Variableexpense_getObject_v2_Response_mPayload(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

Variableexpense_getObject_v2_Response_mPayload::Variableexpense_getObject_v2_Response_mPayload() {
    this->initializeModel();
}

Variableexpense_getObject_v2_Response_mPayload::~Variableexpense_getObject_v2_Response_mPayload() {}

void Variableexpense_getObject_v2_Response_mPayload::initializeModel() {

    m_obj_variableexpense_isSet = false;
    m_obj_variableexpense_isValid = false;
}

void Variableexpense_getObject_v2_Response_mPayload::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void Variableexpense_getObject_v2_Response_mPayload::fromJsonObject(QJsonObject json) {

    m_obj_variableexpense_isValid = ::Ezmaxapi::fromJsonValue(m_obj_variableexpense, json[QString("objVariableexpense")]);
    m_obj_variableexpense_isSet = !json[QString("objVariableexpense")].isNull() && m_obj_variableexpense_isValid;
}

QString Variableexpense_getObject_v2_Response_mPayload::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject Variableexpense_getObject_v2_Response_mPayload::asJsonObject() const {
    QJsonObject obj;
    if (m_obj_variableexpense.isSet()) {
        obj.insert(QString("objVariableexpense"), ::Ezmaxapi::toJsonValue(m_obj_variableexpense));
    }
    return obj;
}

Variableexpense_ResponseCompound Variableexpense_getObject_v2_Response_mPayload::getObjVariableexpense() const {
    return m_obj_variableexpense;
}
void Variableexpense_getObject_v2_Response_mPayload::setObjVariableexpense(const Variableexpense_ResponseCompound &obj_variableexpense) {
    m_obj_variableexpense = obj_variableexpense;
    m_obj_variableexpense_isSet = true;
}

bool Variableexpense_getObject_v2_Response_mPayload::is_obj_variableexpense_Set() const{
    return m_obj_variableexpense_isSet;
}

bool Variableexpense_getObject_v2_Response_mPayload::is_obj_variableexpense_Valid() const{
    return m_obj_variableexpense_isValid;
}

bool Variableexpense_getObject_v2_Response_mPayload::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_obj_variableexpense.isSet()) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool Variableexpense_getObject_v2_Response_mPayload::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_obj_variableexpense_isValid && true;
}

} // namespace Ezmaxapi
